# Generated by Django 3.2.3 on 2021-05-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_no',
            field=models.IntegerField(),
        ),
    ]
