# Generated by Django 3.2.3 on 2021-05-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_event_max_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(default='default.jpg', upload_to='banners'),
        ),
    ]
